---
title: "Reciprocal relationships, reverse causality, and temporal ordering: Testing theories with cross-lagged panel models"
author:
  - Charles C. Lanfear
  - Thiago R. Oliveira
format: pdf
editor: source
execute:
  echo: false
  warning: false
  message: false
---

```{r setup}
# Just here to make sure it renders in R
```


> State something to the effect that we attempt to, whenever possible, illustrate graphically rather than using equations.


```{tikz fig-2_classic-clpm, echo = FALSE, fig.cap = "Directed acyclic graph representation of classic CLPM"}
\usetikzlibrary{positioning}
\definecolor{black}{HTML}{000000}
\tikzset{
    > = stealth,
    every node/.append style = {
        draw = none
    },
    every path/.append style = {
        arrows = ->,
        draw = black,
        fill = none
    },
    hidden/.style = {
        draw = black,
        shape = circle,
        inner sep = 1pt
    }
}
\tikz{
    \node (y1) at (0,2) {$Y_1$};
    \node (y2) at (2,2) {$Y_2$};
    \node (y3) at (4,2) {$Y_3$};
    \node (x1) at (0,0) {$X_1$};
    \node (x2) at (2,0) {$X_2$};
    \node (x3) at (4,0) {$X_3$};
    \path (x1) edge (x2);
    \path (x2) edge (x3);
    \path (x1) edge (y2);
    \path (x2) edge (y3);
    \path (y1) edge (y2);
    \path (y2) edge (y3);
    \path (y1) edge (x2);
    \path (y2) edge (x3);
  }
```


```{tikz fig-3_contemporaneous-clpm, echo = FALSE, fig.cap = "CLPM with contemporaneous effects"}
\usetikzlibrary{positioning}
\definecolor{black}{HTML}{000000}
\tikzset{
    > = stealth,
    every node/.append style = {
        draw = none
    },
    every path/.append style = {
        arrows = ->,
        draw = black,
        fill = none
    },
    hidden/.style = {
        draw = black,
        shape = circle,
        inner sep = 1pt
    }
}
\tikz{
    \node (y1) at (0,2) {$Y_1$};
    \node (y2) at (2,2) {$Y_2$};
    \node (y3) at (4,2) {$Y_3$};
    \node (x1) at (0,0) {$X_1$};
    \node (x2) at (2,0) {$X_2$};
    \node (x3) at (4,0) {$X_3$};
    \path (x1) edge (x2);
    \path (x2) edge (x3);
    \path (x1) edge (y2);
    \path (x2) edge (y3);
    \path (y1) edge (y2);
    \path (y2) edge (y3);
    \path (y1) edge (x2);
    \path (y2) edge (x3);
    
    \path (x1) edge (y1);
    \path (x2) edge (y2);
    \path (x3) edge (y3);
  }
```


## Discordance between theory and data

> Probably best to approach this with Rohrer's framing that "true causal timing" should prob be abandoned and replaced with a well-defined estimand; the timing is a choice, e.g., what is the correct causal timing for the effect of drinking a pint on your judgment? Consider this effect at 20 seconds, 20 minutes, and 20 hours. What about on your thirst or your headache? Strong theory---whether from knowledge of biological mechanisms or personal experience---informs what sort of causal timings are of interest. This framing is useful because it allows us to hammer on theory even more; you can't just toss variables in and assume what you see is the "true process". Authors need to make an argument that the time lag they're studying is useful and can be studied with the data they have.

> This also sets up an important interpretation point raised by Rohrer: discrepant results between studies may purely be due to different time lags. Old lit on this, e.g., GOllob & Reichardt 1987

Theory is recursive and operates at some defined pace---often discrete but sometimes continuous---but practical limitations of measurement result in snapshots or waves of data. The widths of time intervals between waves are usually determined by pragmatic considerations rather than theory, and thus the timing of observations rarely corresponds to the timing we expect in our theories. Often timing is inconsistent across variables as well, e.g., measures describing activities in the past year sit alongside measures of present perceptions. More generally, we can imagine the discordance between our theoretical model and our empirical data collection as a missing data or latent variable problem as illustrated in @fig-time-dag-unobs. As noted, in the real world, time is continuous, so one might imagine there exists an infinite number of these "missing waves" between observations. Whether explicit or not, researchers alway make assumption about the way variables and relationships operate within these unobserved intervals. Theory should and sometimes even does provide a guide to what assumptions are reasonable to make.

```{tikz fig-time-dag-unobs, echo = FALSE, fig.cap = "A theoretical model of cross-lagged effects with incompletely observed periods."}
\usetikzlibrary{positioning}
\definecolor{black}{HTML}{000000}
\tikzset{
    > = stealth,
    every node/.append style = {
        draw = none
    },
    every path/.append style = {
        arrows = ->,
        draw = black,
        fill = none
    },
    hidden/.style = {
        draw = black,
        shape = circle,
        inner sep = 1pt
    }
}
\tikz{
    \node (y1) at (0,2) {$Y_1$};
    \node[hidden] (y15) at (2,2) {$Y_{1.5}$};
    \node (y2) at (4,2) {$Y_2$};
    \node[hidden] (y25) at (6,2) {$Y_{2.5}$};
    \node (y3) at (8,2) {$Y_3$};
    \node (x1) at (0,0) {$X_1$};
    \node[hidden] (x15) at (2,0) {$X_{1.5}$};
    \node (x2) at (4,0) {$X_2$};
    \node[hidden] (x25) at (6,0) {$X_{2.5}$};
    \node (x3) at (8,0) {$X_3$};
    \path (x1) edge (x15);
    \path (x15) edge (x2);
    \path (x2) edge (x25);
    \path (x25) edge (x3);
    \path (x1) edge (y15);
    \path (x15) edge (y2);
    \path (x2) edge (y25);
    \path (x25) edge (y3);
    \path (y1) edge (y15);
    \path (y15) edge (y2);
    \path (y2) edge (y25);
    \path (y25) edge (y3);
    \path (y1) edge (x15);
    \path (y15) edge (x2);
    \path (y2) edge (x25);
    \path (y25) edge (x3);
  }
```

For simplicity, let us assume that in both example cases we have three waves of panel data with yearly waves of observation and continuous measures of our concepts. In our first example---the reciprocal effects of perceived disorder and fear of crime---both perceived disorder and fear of crime are measured at survey time with continuous measures derived from batteries of multiple indicators. In our second example---the effect of employment on offending and attendant reverse causality---employment is measured as the proportion of time spent employed in the last year and offending is a self-reported variety score of offenses committed in the past year.

> Define estimands here but make them ones people really want not ones that are easy to estimate, e.g., employment -> offending is prob roughly instantaneous but measurement means time-varying confounding will be serious problem. Could expand thinking about disorder as it doesn't exactly have time varying confounding unless one is interested in real exposure to disorder, which we know happened in past, but has an uncertain time association with perceptions.

> For employment, if your theory is control theory that says employment restrains crime by keeping you busy, you can an instantaneous contemporaneous effect. That's a challenge for CLPMs!

When observation periods correspond in some way to the speed at which causal processes are believed to operate, theory may imply that you can rule out reciprocal effects or reverse causality. For example, if employment were measured as "Are you presently employed?" we could assume employment can be affected by past-year offending but employment cannot affect past-year offending. In neither of our present examples, however, do our empirical observation periods align with the theoretical causal process.

> Focus will be on when processes we are interested in are faster than our data are observed. When your data are more granular, it is not a problem, because you can either aggregate the data or, better yet, specify more complicated lag structures.

For our first example of the reciprocal effects of fear of crime and disorder perceptions, we expect that both processes of updating occur more rapidly than over course of a year---more quickly, even, than could be captured with *daily* data. Convincingly ruling out reciprocality would require biophysical measurements in a laboratory, an approach which would come at a cost of construct and external validity (i.e., real disorder out in the world). For our second example of employment and offending, we expect the process to occur less quickly (e.g., there is a delay between when someone is caught offending and when they are fired from their job) but either employment or offending could have occurred anywhere throughout the year covered by the measurement. If we decreased gaps between waves---perhaps to daily observations---we could convincingly rule out reverse causality, at least for the contemporaneous effect of employment on offending, e.g., the "involvement" effect in Hirschi's control theory (Hirschi 1969). Thus, in both cases, our expectations for the empirical associations in our data do not correspond to a recursive causal model (i.e., a DAG). As a result, FIGXXX illustrates that we are confident about the the direction of the lagged and cross-lagged relationships but uncertain about the direction of contemporaneous relationships, here represented by the dashed and double-headed arrows.


```{tikz fig-time-dag-obs, echo = FALSE, fig.cap = "A theoretical model of cross-lagged effects with ambiguous contemporaneous relations."}
\usetikzlibrary{positioning}
\definecolor{black}{HTML}{000000}
\tikzset{
    > = stealth,
    every node/.append style = {
        draw = none
    },
    every path/.append style = {
        arrows = ->,
        draw = black,
        fill = none
    },
    hidden/.style = {
        draw = black,
        shape = circle,
        inner sep = 1pt
    }
}
\tikz{
    \node (y1) at (0,2) {$Y_1$};
    \node (y2) at (2,2) {$Y_2$};
    \node (y3) at (4,2) {$Y_3$};
    \node (x1) at (0,0) {$X_1$};
    \node (x2) at (2,0) {$X_2$};
    \node (x3) at (4,0) {$X_3$};
    
    \path (x1) edge (x2);
    \path (x2) edge (x3);
    
    \path (x1) edge (y2);
    \path (x2) edge (y3);
    
    \path (y1) edge (y2);
    \path (y2) edge (y3);
    
    \path (y1) edge (x2);
    \path (y2) edge (x3);
    
    \path (x1) edge [bend right=60, arrows = <->, dashed] (y1);
    \path (x2) edge [bend right=60, arrows = <->, dashed] (y2);
    \path (x3) edge [bend right=60, arrows = <->, dashed] (y3);
  }
```


### Temporality and composite variables

Before proceeding to the statistical model, it is necessary to discuss problems that can result from different measurement strategies common in panel studies. How problematic a temporally misaligned measurement is depends on the nature of the measurement. For this purpose, will we distinguish between two types of measure, which we will call *instantaneous variables* and *period measures*. An instantaneous measure is one where the measured values correspond to some single instant in time (or at least an exceedingly short period). Our perceived disorder and fear of crime variables are examples of instantaneous measures, as they would typically be measured using respondent perceptions at survey time. This situation corresponds roughly to that depicted in @fig-time-dag-unobs and be addressed with conventional approaches to causal inference with DAGs.

> Instantaneous measures have an advantage that you can easily define a counterfactual and not worry so much about late confounding even cross-lag confounding; that stuff is all post-treatment issues. But it still requires some assumptions about how the instant measure relates to the proximate causal one varying over time, e.g., about how stable it is.

In contrast, a period measure is one where the measured value corresponds to some deterministic sum (or other aggregate) calculated over a specified period of time. A variety score of offenses committed over the past year and proportion of time spent employed in the past year are both examples of composite period measures. When our observation periods do not correspond to the timing of our underlying causal model, these period measures become what we will call *composite period variables*. They are a composite because the measured value is a deterministic sumof values that would be obtained by dividing the observation period up into arbitrary smaller intervals and aggregating across them. This situation, appearing in @fig-app-latent, produces challenges that are not well recognized in the literature and sometimes difficult to address (see Berrie et al. 2025). 


> Between these two types of measures are what Mulder et al. refer to as "time aggregation" of variables, where the measurement represents some average over the time period. They focus on survey measures asking respondents to report how they felt on average over a period of time. It seems like quite a stretch to consider these composite variables, so it would be better to approach them with common thinking around recall bias.

```{tikz, label=fig-app-latent, fig.cap = "Reciprocality due to composite period variable. Circled variables are latent. Double-arrows indicate observed variables are composite variables determined by their parents"}
\usetikzlibrary{positioning}
\usetikzlibrary{decorations.pathreplacing}
\definecolor{black}{HTML}{000000}
\tikzset{
    > = stealth,
    every node/.append style = {
        draw = none
    },
    every edge/.append style = {
        arrows = ->,
        fill = none
    },
    hidden/.style = {
        draw = black,
        shape = circle,
        inner sep = 1pt
    }
}
\tikz{

    \draw[|-|] (-0.6,4.25) -- (1.8,4.25);
    \draw[-|] (1.8,4.25) -- (4.2,4.25);
    \draw[-|] (4.2,4.25) -- (6.6,4.25);
    
    \draw [decorate,decoration={brace,amplitude=5pt,mirror,raise=1ex}] (-0.6,4.25) -- (0.6,4.25) node[midway,yshift=-1.5em]{A};
    \draw [decorate,decoration={brace,amplitude=5pt,mirror,raise=1ex}] (0.6,4.25) -- (1.8,4.25) node[midway,yshift=-1.5em]{B};
    \draw [decorate,decoration={brace,amplitude=5pt,mirror,raise=1ex}] (1.8,4.25) -- (3,4.25) node[midway,yshift=-1.5em]{A};
    \draw [decorate,decoration={brace,amplitude=5pt,mirror,raise=1ex}] (3,4.25) -- (4.2,4.25) node[midway,yshift=-1.5em]{B};
    \draw [decorate,decoration={brace,amplitude=5pt,mirror,raise=1ex}] (4.2,4.25) -- (5.4,4.25) node[midway,yshift=-1.5em]{A};
    \draw [decorate,decoration={brace,amplitude=5pt,mirror,raise=1ex}] (5.4,4.25) -- (6.6,4.25) node[midway,yshift=-1.5em]{B};
    
    
    \node[align=center] (obs1) at (-2,4.25) {Time\\Intervals};
    \node[align=center] (obs1) at (-2,1.5) {Latent\\Causal\\Model};
    %\node[align=center] (obs1) at (-2,-2) {Observed\\Associations};%
    
    \node[align=center] (obs1) at (-0.6,4.75) {Start};
    \node[align=center] (obs1) at (1.8,4.75) {Observation\\Time 1};
    \node[align=center] (obs1) at (4.2,4.75) {Observation\\Time 2};
    \node[align=center] (obs1) at (6.6,4.75) {Observation\\Time 3};
    
    
    \node (y1) at (0.6,3) {$Y_1$};
    \node (y2) at (3,3) {$Y_2$};
    \node (y3) at (5.4,3) {$Y_3$};
    
    \node[hidden] (y1a) at (0,2) {$Y_{1A}$};
    \node[hidden] (y1b) at (1.2,2) {$Y_{1B}$};
    \node[hidden] (y2a) at (2.4,2) {$Y_{2A}$};
    \node[hidden] (y2b) at (3.6,2) {$Y_{2B}$};
    \node[hidden] (y3a) at (4.8,2) {$Y_{3A}$};
    \node[hidden] (y3b) at (6,2) {$Y_{3B}$};
    
    \node (x1) at (0.6,0) {$X_1$};
    \node (x2) at (3,0) {$X_2$};
    \node (x3) at (5.4,0) {$X_3$};
    
    \node[hidden] (x1a) at (0,1) {$X_{1A}$};
    \node[hidden] (x1b) at (1.2,1) {$X_{1B}$};
    \node[hidden] (x2a) at (2.4,1) {$X_{2A}$};
    \node[hidden] (x2b) at (3.6,1) {$X_{2B}$};
    \node[hidden] (x3a) at (4.8,1) {$X_{3A}$};
    \node[hidden] (x3b) at (6,1) {$X_{3B}$};
    % latent -> obs
       % X->X%
    \draw[->, double] (x1a) to (x1);
    \draw[->, double] (x1b) to (x1);
    \draw[->, double] (x2a) to (x2);
    \draw[->, double] (x2b) to (x2);
    \draw[->, double] (x3a) to (x3); 
    \draw[->, double] (x3b) to (x3); 
    \draw[->, double] (y1a) to (y1);
    \draw[->, double] (y1b) to (y1);
    \draw[->, double] (y2a) to (y2);
    \draw[->, double] (y2b) to (y2);
    \draw[->, double] (y3a) to (y3); 
    \draw[->, double] (y3b) to (y3); 
    % Y->Y%
    \path (y1a) edge (y1b);
    \path (y1b) edge (y2a);
    \path (y2a) edge (y2b);
    \path (y2b) edge (y3a);
    \path (y3a) edge (y3b);
   % X->X%
    \path (x1a) edge (x1b);
    \path (x1b) edge (x2a);
    \path (x2a) edge (x2b);
    \path (x2b) edge (x3a);
    \path (x3a) edge (x3b); 
       % X->Y%
    \path (x1a) edge (y1b);
    \path (x1b) edge (y2a);
    \path (x2a) edge (y2b);
    \path (x2b) edge (y3a);
    \path (x3a) edge (y3b); 
       % Y->X%
    \path (y1a) edge (x1b);
    \path (y1b) edge (x2a);
    \path (y2a) edge (x2b);
    \path (y2b) edge (x3a);
    \path (y3a) edge (x3b); 
  }
```


@fig-app-latent illustrates a case where we are interested in the relationship between two period variables $A$ and $B$. The recall period for data collection encompasses 1 unit of time (e.g., an entire year) but the causal process relating the two period variables operates over smaller intervals (e.g., six months) denoted $A$ and $B$. This is represented by cross-lagged effects between latent $X$ and $Y$ variables occurring across each smaller interval. Because data were only collected at each observation time, the measured values represent a composite period variable combining the values from periods $A$ and $B$. For example, if $Y_1$ is the number of self-reported criminal offenses in a year, it would be the simple sum of offenses $Y_{1A} + Y_1{B}$. While we may know this sum, without additional information, we are uncertain of the value of either $Y_{1A}$ or $Y_1{B}$ (unless $Y_1=0$). Borrowing the notation of Berrie et al. (2025), the double-arrows indicate that $Y_t$ and $X_t$ are *deterministic* variables, i.e., they are fully determined by *some* combination of the underlying latent parent variables, even if we do not know their relative contribution^[If $Y_{tA}$ and/or $Y_{tB}$ contain measurement error, this full measurement error is propagated into the composite variable as well]. Note that despite $X_t = X_{ta} + X_{tb}$, $X_t$ is not a compositional variable as defined by Berrie et al. (2025), because the parents $X_{ta}$ and $X_{tb}$ are not simultaneously determined. Rather, $X_t$ is a composite derived variable where the parents are unobservable or latent.

> It would be useful if we'd discussed consistency and exchangeability (I like ignorability myself). Exchangeability means all units have equal probability of receiving all values of outcome at time of exposure. Consistency means there are not multiple versions of the same-valued tgreatment that produce different potential outcomes.

> Even more useful would be to begin high up discussing counterfactuals and thinking about causal effects in those terms. Prob look at https://www.the100.ci/2025/06/25/reviewer-notes-so-youre-interested-in-lagged-effects/

Composite measures present unique challenges for causal inference (Berrie et al. 2025). 

* Ignorability: Need to deal with all confounders for each parent, but these may be different.
   * Time-varying confounding can be a serious problem as Berrie et al. (2025:475) note: "...if the parent variables occur at different moments in time, it is possible they will have different relationships with the supposed confounders. Indeed, it is possible that a confounder for one parent variable may be a mediator for another, leaving no means to appropriately adjust for confounding without also blocking part of the true causal effect. Identifying the causal effect of a composite derived variable, as with any analysis of multiple exposures, therefore requires no time-varying confounding."
   * In rare case you have a strong theoretical reason to believe a variable affects one parent but is exogenous to the other, you could use it as an instrument to isolate the parent you are interested in, e.g., a randomized employment program affecting only the second half of the year.
* Consistency: One can arrive at the same value of a child treatment variable through multiple combinations of the parent variables.
* Composite variable bias: The estimated average causal effect of the composite variable will be a mean of the average causal effects of the parent variables that is proportionally weighted toward the parent(s) with larger variance(s).




## Statistical Model

Once the theoretical model has been established, one can proceed to developing a statistical model that accounts for the constraints from the research design---including ambiguity about causal directions. Here, path diagrams from the structural equation modeling (SEM) tradition become useful. SEM diagrams encode both causal relations between variables---indicated by single-headed arrows pointing from cause to effect---and unanalyzed, unexplained, or "nuisance" associations---indicated by double-headed arrows pointing between two variables. That is, one explicitly distinguishes between causal relationships and ambiguous associations. Variables with any causal path leading into them are termed "endogenous" variables and those with no causal path leading into them are termed "exogenous". SEM diagrams depart from most DAGs by depicting the residuals or unexplained variation of endogenous variables as latent variables causally affecting the observed variable.

> Thiago: Bollen & Pearl 2009 provide a nice discussion about the notational relationship between SEM path diagrams and DAGs.We should also look at Imai & Kim's three papers on causal inference with panel data. They use DAGs and they're so well written. I don't think they discuss reciprocal effects at all (could be wrong), but we could rely on them from a notational point of view in using DAGs to depict temporal processes.

> Chuck: I need to read the above and revisit other materials to clean my language up. I am not confident the way I distinguish between "causal" and the rest of the model corresponds to the classic SEM distinction of structural model vs. measurement model, i.e., the residual covariances are still part of the structural model, I think.

Our recommendation is that the causal part of the SEM diagram should be recursive, corresponding as closely as possible to the theoretical model. Reciprocal simultaneous effects should generally be avoided as they require strong identifying assumptions, e.g., valid and relevant instrumental variables (Green 2003; XXXX). When the timing of observation results in ambiguity regarding the causal direction within any given time period---such as when periods $t=1.5$ and $t=2.5$ were not observed in Fig XXX---we encode this ambiguity as an unanalyzed covariance between the variables in question. When the timing of observations closely corresponds to theory, these covariances are unnecessary and the resulting statistical model similarly corresponds directly to the theoretical model.

For both examples, following these guidelines leads us to the "classic" three-wave CLPM depicted in FIGXX. The causal relations consist of two sets of relationships: a) lagged (autoregressive) effects of variables in one period on their value in the next period, e.g., $x_{t} \rightarrow x_{t+1}$, and b) cross-lagged effects of variables in one period on the other variable in the next period, e.g., $x_{t} \rightarrow y_{t+1}$. The non-causal relations consist of two sets of covariances: a) between the exogenous $x_1$ and $y_1$, which merely permit the predictors to be correlated as in any typical regression model, and b) between the residuals of the endogenous variables ($\zeta_t$ and $\epsilon_t$)^[Omitting the residual covariances yields the oft-maligned cross-lagged correlations model.]. The residual covariances account for the ambiguous contemporaneous association between $x_t$ and $y_t$ but cannot tell us the direction of any causal effect between the two variables.

```{tikz sem-clpm, fig.cap = "SEM path diagram representation of three-wave CLPM"}
\usetikzlibrary{positioning}
\definecolor{black}{HTML}{000000}
\tikzset{
    > = stealth,
    every node/.append style = {
        draw = none
    },
    every path/.append style = {
        arrows = ->,
        draw = black,
        fill = none
    },
    hidden/.style = {
        draw = black,
        shape = circle,
        inner sep = 1pt
    }
}
\tikz{
    \node (x1) at (0,2) {$X_1$};
    \node (x2) at (2,2) {$X_2$};
    \node (x3) at (4,2) {$X_3$};
    \node (y1) at (0,0) {$Y_1$};
    \node (y2) at (2,0) {$Y_2$};
    \node (y3) at (4,0) {$Y_3$};
    \node (ex2) at (2.5,3) {$\zeta_{2}$};
    \node (ey2) at (2.5,-1) {$\epsilon_{2}$};
    \node (ex3) at (4.5,3) {$\zeta_{3}$};
    \node (ey3) at (4.5,-1) {$\epsilon_{3}$};
    \path (x1) edge (x2);
    \path (x2) edge (x3);
    \path (x1) edge (y2);
    \path (x2) edge (y3);
    \path (y1) edge (y2);
    \path (y2) edge (y3);
    \path (y1) edge (x2);
    \path (y2) edge (x3);
    \path (x1) edge [bend right=60, arrows = <->] (y1);
    \path (ex2) edge [bend left=45, arrows = <->] (ey2);
    \path (ex3) edge [bend left=45, arrows = <->] (ey3);
    \path (ex2) edge (x2);
    \path (ex3) edge (x3);
    \path (ey2) edge (y2);
    \path (ey3) edge (y3);
  }
```

In principle, the classic CLPM permits identification of the cross-lagged effects under conventional assumptions common to most causal inference approaches (see Morgan & Winship; Wooldridge) and in paticular mediation analysis, e.g. sequential ignorability . In application, researchers using the classic CLPM may easily fall prey to a number of common issues that, if unaddressed, result in misleading inferences. Rather than providing an exhaustive list of problems that can arise with CLPMs, we focus on the three key issues we believe are the most important for researchers in developmental and life course criminology to be aware of due to the frequency with which they will be encountered and the severity of their effect on inferences: a) improperly specified temporal order, b) unobserved heterogeneity, c) insufficient inter-temporal variation. 

## For other sections:

* Mulder et al. (2025): "low process coverage" occurs when intervals that are too long to capture process combine with time aggregated variables to make it so an insufficient amount of the underlying continuous process is captured.
* Given timing issues, longitudinal data are much better equipped to study the key elements of life course theories (e.g., trajectories and turning points) than rapid and transient processes. Prob be good to say you simply aren't going to get anything useful from yearly panel data on fast moving things.
* Exogenous shocks and interventions can bypass a lot of these problems.
* Recommendations for data collection include having people fill out repeated or momentary assessments, calendars, etc.